CREATE TABLE  acl_sid (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  PRINCIPAL tinyint(1) NOT NULL,
  SID varchar(100) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT unique_uk_class UNIQUE (SID,PRINCIPAL)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE  acl_class (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CLASS varchar(100) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UNIQUE_UK_2 UNIQUE(CLASS)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  acl_object_identity (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  OBJECT_ID_CLASS bigint(20) NOT NULL,
  OBJECT_ID_IDENTITY bigint(20) NOT NULL,
  PARENT_OBJECT bigint(20) DEFAULT NULL,
  OWNER_SID bigint(20) DEFAULT NULL,
  ENTRIES_INHERITING tinyint(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY FOREIGN_FK_1 (PARENT_OBJECT),
  KEY FOREIGN_FK_2 (OBJECT_ID_CLASS),
  KEY FOREIGN_FK_3 (OWNER_SID),
  CONSTRAINT FOREIGN_FK_1 FOREIGN KEY (PARENT_OBJECT) REFERENCES acl_object_identity (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FOREIGN_FK_2 FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES acl_class (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FOREIGN_FK_3 FOREIGN KEY (OWNER_SID) REFERENCES acl_sid (ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=latin1;

CREATE TABLE  acl_entry (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  ACL_OBJECT_IDENTITY bigint(20) NOT NULL,
  ACE_ORDER int(11) NOT NULL,
  SID bigint(20) NOT NULL,
  MASK int(11) NOT NULL,
  GRANTING tinyint(1) NOT NULL,
  AUDIT_SUCCESS tinyint(1) NOT NULL,
  AUDIT_FAILURE tinyint(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY FOREIGN_FK_4 (ACL_OBJECT_IDENTITY),
  KEY FOREIGN_FK_5 (SID),
  CONSTRAINT FOREIGN_FK_4 FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES acl_object_identity (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FOREIGN_FK_5 FOREIGN KEY (SID) REFERENCES acl_sid (ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=181 DEFAULT CHARSET=latin1;

CREATE TABLE  authorities (
  USERNAME varchar(50) NOT NULL,
  AUTHORITY varchar(50) NOT NULL,
  KEY IX_AUTH_USERNAME (USERNAME,AUTHORITY)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE  contacts (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  CONTACT_NAME varchar(50) NOT NULL,
  EMAIL varchar(50) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=latin1;

CREATE TABLE  users (
  USERNAME varchar(50) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  ENABLED tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;